#!/usr/bin/env node
// Validates a .env-style file against @sl/api's own zod schema
// (apps/api/src/config/env.ts's `loadEnv`), without loading it into this
// process's real environment or requiring the api app to be built.
//
// Usage:
//   node infra/scripts/check-env.mjs <path-to-env-file>
// Node >= 22.6 strips the imported .ts file's types natively (no flag
// needed as of 22's later releases; on an older Node 22.x that still gates
// it, add --experimental-strip-types, or run via the repo's own tsx:
//   apps/api/node_modules/.bin/tsx infra/scripts/check-env.mjs <path-to-env-file>
//
// Exit codes: 0 valid, 1 invalid (schema errors printed), 2 usage/IO error.

import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { loadEnv } from '../../apps/api/src/config/env.ts';

/**
 * Minimal, dependency-free .env parser (dotenv-compatible subset): ignores
 * blank lines and `#` comments, strips matching surrounding quotes from a
 * value, and expands literal `\n` inside a value to a real newline (how the
 * PEM keys generated by `pnpm --filter @sl/api keys:generate` are stored on
 * one line — matching dotenv's own behaviour for double-quoted values).
 */
function parseEnvFile(path) {
  const raw = readFileSync(path, 'utf8');
  /** @type {Record<string, string>} */
  const out = {};

  for (const rawLine of raw.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;

    const eq = line.indexOf('=');
    if (eq === -1) continue;

    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();

    const quoted =
      (value.startsWith('"') && value.endsWith('"') && value.length >= 2) ||
      (value.startsWith("'") && value.endsWith("'") && value.length >= 2);
    if (quoted) value = value.slice(1, -1);

    // Strip an inline, unquoted `# comment` (dotenv semantics: only when
    // the value wasn't quoted — a quoted value may legitimately contain '#').
    if (!quoted) {
      const hashIdx = value.indexOf(' #');
      if (hashIdx !== -1) value = value.slice(0, hashIdx).trim();
    }

    out[key] = value.replace(/\\n/g, '\n');
  }

  return out;
}

function main() {
  const target = process.argv[2];
  if (!target) {
    console.error('Usage: tsx infra/scripts/check-env.mjs <path-to-env-file>');
    process.exit(2);
  }

  const path = resolve(process.cwd(), target);
  if (!existsSync(path)) {
    console.error(`env file not found: ${path}`);
    process.exit(2);
  }

  const parsed = parseEnvFile(path);

  try {
    const env = loadEnv(parsed);
    const redactedDbUrl = env.DATABASE_URL.replace(/:[^:@/]*@/, ':***@');
    console.log(`OK  ${target} is valid against apps/api/src/config/env.ts's schema.`);
    console.log(`    NODE_ENV=${env.NODE_ENV}  PORT=${env.PORT}  DATABASE_URL=${redactedDbUrl}`);

    // Not part of the zod schema (read directly by packages/db/src/seed.ts),
    // but worth flagging since a missing pair silently skips seeding the
    // super admin rather than failing loudly.
    if (!parsed.SEED_ADMIN_EMAIL || !parsed.SEED_ADMIN_PASSWORD) {
      console.log('    note: SEED_ADMIN_EMAIL/SEED_ADMIN_PASSWORD not both set — `pnpm --filter @sl/db seed` will skip the super admin.');
    }
    process.exit(0);
  } catch (err) {
    console.error(`INVALID  ${target} failed validation:\n`);
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
}

main();
